name: Build and Release with Nuitka

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ✅ pip 缓存加速
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.LOCALAPPDATA }}\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # ✅ 统一版本提取变量
      - name: Extract version
        id: version
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
          else
            VERSION="0.0.0.0"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      # ✅ Nuitka 编译
      - name: Compile with Nuitka (non-onefile)
        run: |
          python -m nuitka main.py `
            --windows-file-version=${{ steps.version.outputs.version }} `
            --windows-product-version=${{ steps.version.outputs.version }}


      # ✅ 使用变量统一输出目录
      - name: Create top-level directory
        run: |
          $outputDir = "DisplaySwitcher"
          New-Item -ItemType Directory -Path $outputDir
          Copy-Item -Path build/main.dist/* -Destination $outputDir -Recurse
        shell: pwsh

      # ✅ 使用变量创建 zip 包
      - name: Create zip for release
        run: |
          $version = "${{ steps.version.outputs.version }}"
          Compress-Archive -Path "DisplaySwitcher" -DestinationPath "DisplaySwitcher-$version.zip"
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DisplaySwitcher
          path: DisplaySwitcher-*.zip
          include-hidden-files: true

      # ✅ 条件触发发布
      - name: Upload zip to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: DisplaySwitcher-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
