name: Build and Release with Nuitka

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Compile with Nuitka (non-onefile)
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: standalone
          include-data-files: icon.ico=icon.ico
          windows-console-mode: disable
          windows-icon-from-ico: icon.ico
          enable-plugins: pyside6
          output-file: DisplaySwitcher.exe

      - name: Create top-level directory
        run: |
          $outputDir = "DisplaySwitcher"
          New-Item -ItemType Directory -Path $outputDir
          Copy-Item -Path build/main.dist/* -Destination $outputDir -Recurse
        shell: pwsh

      - name: Create zip for release
        run: |
          $version = "$env:GITHUB_REF".Replace("refs/tags/", "")
          Compress-Archive -Path "DisplaySwitcher" -DestinationPath "DisplaySwitcher-$version.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DisplaySwitcher
          path: DisplaySwitcher-*.zip
          include-hidden-files: true

      - name: Upload zip to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: DisplaySwitcher-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
